/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalpha;

/**
 *
 * @author LBRENESV
 */
public class MoleGrid extends javax.swing.JPanel {

    /**
     * Creates new form interfaz
     */
    public MoleGrid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();
        b1_1 = new javax.swing.JButton();
        b2_1 = new javax.swing.JButton();
        b3_1 = new javax.swing.JButton();
        b1_2 = new javax.swing.JButton();
        b1_3 = new javax.swing.JButton();
        b2_2 = new javax.swing.JButton();
        b2_3 = new javax.swing.JButton();
        b3_3 = new javax.swing.JButton();
        b3_2 = new javax.swing.JButton();
        points = new javax.swing.JLabel();

        texto.setText("Puntaje:");

        b1_1.setBackground(new java.awt.Color(255, 255, 255));
        b1_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b1_1.setText("(1,1)");
        b1_1.setAlignmentY(0.0F);
        b1_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b1_1.setIconTextGap(0);
        b1_1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        b1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1_1ActionPerformed(evt);
            }
        });

        b2_1.setBackground(new java.awt.Color(255, 255, 255));
        b2_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b2_1.setText("(2,1)");
        b2_1.setAlignmentY(0.0F);
        b2_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b2_1.setIconTextGap(0);
        b2_1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        b2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2_1ActionPerformed(evt);
            }
        });

        b3_1.setBackground(new java.awt.Color(255, 255, 255));
        b3_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b3_1.setText("(3,1)");
        b3_1.setAlignmentY(0.0F);
        b3_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b3_1.setIconTextGap(0);
        b3_1.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b1_2.setBackground(new java.awt.Color(255, 255, 255));
        b1_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b1_2.setText("(1,2)");
        b1_2.setAlignmentY(0.0F);
        b1_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b1_2.setIconTextGap(0);
        b1_2.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b1_3.setBackground(new java.awt.Color(255, 255, 255));
        b1_3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b1_3.setText("(1,3)");
        b1_3.setToolTipText("");
        b1_3.setAlignmentY(0.0F);
        b1_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b1_3.setIconTextGap(0);
        b1_3.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b2_2.setBackground(new java.awt.Color(255, 255, 255));
        b2_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b2_2.setText("(2,2)");
        b2_2.setAlignmentY(0.0F);
        b2_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b2_2.setIconTextGap(0);
        b2_2.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b2_3.setBackground(new java.awt.Color(255, 255, 255));
        b2_3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b2_3.setText("(2,3)");
        b2_3.setAlignmentY(0.0F);
        b2_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b2_3.setIconTextGap(0);
        b2_3.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b3_3.setBackground(new java.awt.Color(255, 255, 255));
        b3_3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b3_3.setText("(3,3)");
        b3_3.setAlignmentY(0.0F);
        b3_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b3_3.setIconTextGap(0);
        b3_3.setMargin(new java.awt.Insets(1, 1, 1, 1));

        b3_2.setBackground(new java.awt.Color(255, 255, 255));
        b3_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        b3_2.setText("(3,2)");
        b3_2.setAlignmentY(0.0F);
        b3_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b3_2.setIconTextGap(0);
        b3_2.setMargin(new java.awt.Insets(1, 1, 1, 1));

        points.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(points))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(points))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b1_2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b1_3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b2_3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b3_2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(b3_3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2_1ActionPerformed

    private void b1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1_1;
    private javax.swing.JButton b1_2;
    private javax.swing.JButton b1_3;
    private javax.swing.JButton b2_1;
    private javax.swing.JButton b2_2;
    private javax.swing.JButton b2_3;
    private javax.swing.JButton b3_1;
    private javax.swing.JButton b3_2;
    private javax.swing.JButton b3_3;
    private javax.swing.JLabel points;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
